runtime: nodejs22

env_variables:
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyA9Fkhnjg1_kN2lfl3qlfjeTDl5iDadltw"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "iron-entropy-493707-f2.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "iron-entropy-493707-f2"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "iron-entropy-493707-f2.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "617547024075"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:617547024075:web:ee2e2d222b7b2be9e3bd4e"

automatic_scaling:
  min_instances: 0
  max_instances: 1